# generated by datamodel-codegen:
#   filename:  chat_ast.json

from __future__ import annotations

from collections.abc import Sequence

from pydantic import BaseModel, ConfigDict, RootModel


class TopItem(BaseModel):
    """
    @...
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    Header: str


class TopItem1(BaseModel):
    """
    ...
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    MainTier: str


class TopItem2(BaseModel):
    """
    %...
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    DependentTier: str


class TopItem3(BaseModel):
    """
    An error!
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    UnrecognizedTier: str


class Top(RootModel[TopItem | TopItem1 | TopItem2 | TopItem3]):
    root: TopItem | TopItem1 | TopItem2 | TopItem3
    """
    Top-level line.
    """


class Chat(BaseModel):
    """
    A CHAT transcript.
    """

    tops: Sequence[Top]
    """
    All the top level lines.
    """
