# generated by datamodel-codegen:
#   filename:  chat_ast.json

from __future__ import annotations

from collections.abc import Sequence

from pydantic import BaseModel, ConfigDict, RootModel


class Top1(BaseModel):
    """
    @...
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    Header: str


class Top2(BaseModel):
    """
    ...
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    MainTier: str


class Top3(BaseModel):
    """
    %...
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    DependentTier: str


class Top4(BaseModel):
    """
    An error!
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    UnrecognizedTier: str


class Top(RootModel[Top1 | Top2 | Top3 | Top4]):
    root: Top1 | Top2 | Top3 | Top4
    """
    Top-level line.
    """


class Chat(BaseModel):
    """
    A CHAT transcript.
    """

    tops: Sequence[Top]
    """
    All the top level lines.
    """
